config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :organisations
  resources :shifts
  root "sessions#new"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "logout" => "sessions#destroy"
  get "join/:id/:organisation_id" => "users#join"
  get "leave/:id" => "users#leave"
  get "search" => "shifts#index"
  get "password/reset" => "password_reset#new"
  post "password/reset" => "password_reset#create"
  get "password/reset/edit" => "password_reset#edit"
  patch "password/reset/edit" => "password_reset#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  validates :name, presence: true
  validates :hourly_rate, presence: true, numericality: true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
  attr_accessor :shift_date, :start_time, :finish_time

  before_validation(on: :create) do
    self.start = DateTime.parse("#{shift_date} #{start_time}")
    self.finish = DateTime.parse("#{shift_date} #{finish_time}")
  end

  before_validation(on: :update) do
    self.start = DateTime.parse("#{shift_date} #{start_time}")
    self.finish = DateTime.parse("#{shift_date} #{finish_time}")
  end

  validates :start, presence: true
  validates :finish, presence: true
  validates :break_length, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :organisation, optional: true
  has_many :shifts
  has_secure_password
  validates :name, presence: true
  validates :email_address, uniqueness: true
  validates :password, :confirmation => true
  validates :password_confirmation, presence: true, if: :password_digest_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  def index
    require_user
    @organisations = Organisation.all
  end

  def new
    require_user
    @organisation = Organisation.new
  end

  def create
    require_user
    @organisation = Organisation.new(organisation_params)
    if @organisation.save
      flash[:notice] = "organisation created"
      redirect_to action: "index"
    else
      render "new"
    end
  end

  def edit
    require_user
    @organisation = Organisation.find(params[:id])
  end

  def update
    require_user
    @organisation = Organisation.find(params[:id])
    if @organisation.update(organisation_params)
      flash[:notice] = "organisation updated"
      redirect_to action: "index"
    else
      render "edit"
    end
  end

  def destroy
    require_user
    @organisation = Organisation.find(params[:id])
    @organisation.destroy
    redirect_to action: "index"
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name, :hourly_rate)
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email_address: params[:email_address])
    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "If an account with the email provided was found, we have sent a link to reset your password"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to root_path, alert: "Your token has expired. Please try again"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update!(password_params)
      redirect_to root_path, notice: "Your password has been reset, Please log in"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email_address: params[:session][:email_address])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "logged in successfully"
      redirect_to organisations_path
    else
      flash.now[:alert] = "there was something wong with your credentials"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "you have been logged out"
    redirect_to root_path
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    require_user
    if params[:query_name].present? && params[:query_starts_at].present? && params[:query_ends_at].present?
      @shifts = @shifts = Shift.joins(:user).where("name LIKE ? ", params[:query_name]).where("start BETWEEN ? AND ?", params[:query_starts_at], params[:query_ends_at]).order(start: :desc)
    elsif params[:query_starts_at].present? && params[:query_ends_at]
      @shifts = Shift.where("start BETWEEN ? AND ?", params[:query_starts_at], params[:query_ends_at]).order(start: :desc)
    elsif params[:query_name].present?
      @shifts = Shift.joins(:user).where("name LIKE ?", params[:query_name]).order(start: :desc)
    else
      @shifts = Shift.all.order(start: :desc)
    end
  end

  def new
    require_user
    @shift = Shift.new
  end

  def create
    require_user
    @shift = Shift.new(shift_params)
    @shift.user_id = current_user.id
    if @shift.save
      flash[:notice] = "shift created!"
      redirect_to :action => "index"
    else
      render "new"
    end
  end

  def edit
    require_user
    @shift = Shift.find(params[:id])
  end

  def update
    require_user
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      redirect_to :action => "index"
    else
      render "edit"
    end
  end

  def destroy
    require_user
    @shift = Shift.find(params[:id]).destroy
    redirect_to :action => "index"
  end

  private

  def shift_params
    params.require(:shift).permit(:start, :finish, :break_length, :user_id, :shift_date, :start_time, :finish_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "user created successfully"
      session[:user_id] = @user.id
      redirect_to controller: :organisations, action: :index
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def edit
    require_user
    @user = User.find(params[:id])
  end

  def update
    require_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "user updated"
      redirect_to controller: :organisations, action: :index
    else
      render "edit"
    end
  end

  def join
    require_user
    @user = User.find(params[:id])
    if params[:organisation_id].present?
      @user.organisation = Organisation.find(params[:organisation_id])
      @user.save!
      redirect_to controller: :organisations, action: :index
    else
      redirect_to controller: :organisations, action: :index
    end
  end

  def leave
    require_user
    @user = User.find(params[:id])
    @user.organisation = nil
    @user.shifts.destroy_all
    @user.save!
    redirect_to controller: :organisations, action: :index
  end

  private

  def user_params
    params.require(:user).permit(:name, :email_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkforceBackendChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_with model:@organisation do |form|%>
  <% if form.object.errors.any?%>
     <% form.object.errors.full_messages.each do |msg|%>
      <h3> <%= msg%> </h3>
     <%end%>
  <%end%>
  <div>
  <%= form.label :name%>
  <br/>
  <%= form.text_field :name, id: :organisation_name%>
  </div>
  <div>
  <%= form.label :hourly_rate%>
  <br/>
  <%= form.number_field :hourly_rate, step: 0.01,  id: :organisation_hourly_rate%>
  </div>
  <%=form.submit%>
<%end%> 

app/views/organisations/edit.html.erb
<%= render "shared/header"%>
<%=render "form", locals: {organisation: @organisation}%>
<%= link_to 'Delete', 
  { controller: "organisations", action: "destroy", id: @organisation.id }, 
  data: { confirm: 'Are you sure?' }, 
  method: :delete %>
  <br/>
<%= link_to "Back", {:controller => :organisations, :action => "index"}%>

app/views/organisations/index.html.erb
<%= render "shared/header"%>
<%if !current_user.organisation%>
  <p>You aren't in any Organisations, create one or join one</p>
  <h2>Organisations</h2>
  <ul id="organisations">
    <% @organisations.each do |o|%>
    <li>
      <%=o.name%>
      <%=link_to "edit", {:controller => "organisations", :action => "edit", :id => o.id}%>
      <%=link_to "join", {:controller => "users", :action => "join", :id => current_user.id, :organisation_id => o.id}%>
    </li>
    <%end%>
  </ul>
  <h2> <%=link_to "Create Organisation", {:controller => "organisations", :action => "new"}%> </h2>
<%else%>
  <h2><%=current_user.organisation.name%></h2>
  <p> <%=link_to "View Shifts", {:controller => "shifts", :action => "index"}%> </p>
  <p><%= link_to "Edit", {:controller => "organisations", :action => "edit", :id => current_user.organisation.id}%></p>
  <p> <%= link_to "Leave", {:controller => "users", :action => "leave", :id => current_user.id}%> </p>
<%end%>

app/views/organisations/new.html.erb
<%=render "shared/header"%>
<%=render "form", locals: {organisation: @organisation}%>
<%= link_to "Back", {:controller => "organisations", :action => "index"}%>

app/views/password_reset/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form|%>
  <% if form.object.errors.any?%>
    <% form.object.errors.full_messages.each do |msg|%>
      <h3> <%= msg%> </h3>
    <%end%>
  <%end%>
  <%= form.label :password %>
  <%= form.password_field :password, class: "form-control",placeholder: "password"%>
  <br/>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class: "form_control", placeholder: "password"%>
  <br/>
  <%= form.submit "Reset Password"%>
<%end%>

app/views/password_reset/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |f|%>
<%= f.label "Email"%>
<%= f.email_field :email_address%>
<%= f.submit "Reset Password"%>
<%end%>
<br/>
<%= link_to "back", root_path%>

app/views/shared/_header.html.erb
<h1> <%=link_to "Adnat", {:controller => "organisations", :action => "index"}%> </h1>
<p>Logged in as <%=current_user.name%> <%=link_to "logout", logout_path%> <%=link_to "edit", {:controller => "users", :action => "edit", :id => current_user.id}%> </p>

app/views/shifts/_form.html.erb
<%= form_with model: @shift do |form|%>
  <% if form.object.errors.any?%>
     <% form.object.errors.full_messages.each do |msg|%>
      <h3> <%= msg%> </h3>
     <%end%>
  <%end%>
  <div>
    <%= form.label :shift_date%>
    <%= form.date_field :shift_date%>
  </div>
  <div>
    <%= form.label :start_time%>
    <%= form.time_field :start_time%>
  </div>
  <div>
    <%= form.label :finsh_time%>
    <%= form.time_field :finish_time%>
  </div>
  <div>
    <%= form.label :break_length, "Break length (in Minutes)"%>
    <%= form.number_field :break_length%>
  </div>
  <%=form.submit%>
<%end%>

app/views/shifts/edit.html.erb
<%=render "shared/header"%>
<%= render"form", locals:{shift: @shift}%>

app/views/shifts/index.html.erb
<%= render "shared/header"%>
<h1> <%= current_user.organisation.name%> </h1>
<h2>shifts</h2>
<% @new_shifts = @shifts.filter {|shift| shift.user.organisation === current_user.organisation}%>
<%= form_with url: "/shifts", method: :get do |f|%>
<%= f.label :query_name, "Search for:"%>
<%= f.text_field :query_name%>
<%= f.date_field :query_starts_at%>
<%= f.date_field :query_ends_at%>
<%= f.submit "search"%>
<%end%>
<table>
  <thead>
   <tr>
      <th>Employee Name</th>
      <th>Shift Date</th>
      <th>Start Time</th>
      <th>Finish Time</th>
      <th>Break Length (minutes)</th>
      <th>Hours Worked</th>
      <th>Shift Cost</th>
   </tr>
  </thead>
  <tbody>
    <% @new_shifts.each do |s|%>
      <tr>
        <td> <%= s.user.name%> </td>
        <td> <%= s.start.strftime("%D")%> </td>
        <td> <%= s.start.strftime("%r")%> </td>
        <td> <%= s.finish.strftime("%r")%> </td>
        <td> <%= s.break_length%> </td>
        <% 
        total_hours = ((s.finish.to_time - s.start.to_time) / 1.hour).to_f
        breaklength = s.break_length / 60.to_f
        hours_worked = (total_hours - breaklength)
        shift_cost = hours_worked * s.user.organisation.hourly_rate
        %>
        <td> <%=sprintf('%.1f', hours_worked)%> </td>
        <%
        %>
        <td> <%=number_to_currency(shift_cost, :unit => "$")%> </td>
        <td> <%= link_to 'delete', { controller: "shifts", action: "destroy", id: s.id }, data: { confirm: 'Are you sure?' }, method: :delete %> </td>
        <td> <%= link_to "edit", {:controller => "shifts", action: "edit", id: s.id}%> </td>
      </tr>
    <%end%>
  </tbody>
</table>
<h3> <%= link_to "Create A Shift", {:controller => 'shifts', :action => 'new'}%> </h3>
<%= link_to "Back", {:controller => 'organisations', :action => 'index'}%>

app/views/shifts/new.html.erb
<%=render "shared/header"%>
<%=render "form", locals: {shift: @shift}%>
<%= link_to "Back", {:controller => "organisations", :action => "index"}%>

app/views/users/_form.html.erb
<%= form_with model: @user do |form|%>
  <% if form.object.errors.any?%>
     <% form.object.errors.full_messages.each do |msg|%>
      <h3> <%= msg%> </h3>
     <%end%>
  <%end%>

  <div>
    <%= form.label :name, "Name"%>
    <br/>
    <%= form.text_field :name, id: :user_name%>
  </div>
  
  <div>
    <%= form.label :email_address%>
    <br/>
    <%= form.email_field :email_address, id: :user_email_address%>
  </div>
  
  <div>
    <%= form.label :password%>
    <br/>
    <%= form.password_field :password%>
  </div>
  
  <div>
    <%= form.label :password_confirmation%>
    <br/>
    <%= form.password_field :password_confirmation%>
  </div>
  <br/>
  <%= form.submit %>
<%end%>

app/views/users/edit.html.erb
<%=render "shared/header"%>
<%=render "form", locals: {user: @user}%>
<%= link_to "back", {:controller => "organisations", :action => "index"} %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", locals: {user: @user}%>
<%= link_to "Back", root_path%>